version: 2

models:
  - name: fact_trips
    description: >
      Taxi trips corresponding to fhv.
      The table contains records where both pickup and dropoff locations are valid and known zones. 
      Each record corresponds to a trip uniquely identified by tripid. 